services:
    kafka-service:
        container_name: kafka-service
        image: apache/kafka:3.9.0
        hostname: kafka-service
        environment:
            KAFKA_KRAFT_MODE: "true"  # This enables KRaft mode in Kafka.
            KAFKA_PROCESS_ROLES: controller,broker  # Kafka acts as both broker and controller.
            KAFKA_NODE_ID: 1  # A unique ID for this Kafka instance.
            KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-service:9093"  # Defines the controller voters.
            KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-service:9092
            KAFKA_LOG_DIRS: /var/lib/kafka/data  # Where Kafka stores its logs.
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"  # Kafka will automatically create topics if needed.
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  # Since we’re running one broker, one replica is enough.
            KAFKA_LOG_RETENTION_HOURS: 168  # Keep logs for 7 days.
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0  # No delay for consumer rebalancing.
        ports:
            - "9092:9092"
            - "9093:9093"
        expose:
            - "9092"
            - "9093"


    grafana:
        image: grafana/grafana-enterprise
        container_name: grafana
        volumes:
            - ${STORAGE_DIR}/grafana:/var/lib/grafana
        deploy:
            resources:
                limits:
                    cpus: '0.2'
                    memory: 512M
                reservations:
                    cpus: '0.1'
                    memory: 256M
        ports:
            - '${GRAFANA_PORT}:3000'

    frontend:
        build:
            context: UI
            target: development
            dockerfile: ../docker/react/Dockerfile
        ports:
            - 3000:3000
        volumes:
            - ./UI/src:/code/src
            - /UI/node_modules
        expose:
            - 3306
            - 33060
        deploy:
            resources:
                limits:
                    cpus: '0.2'
                    memory: 512M
                reservations:
                    cpus: '0.1'
                    memory: 256M

include:
    - ./docker/compose/base.yml
