CREATE TABLE IF NOT EXISTS users (
   id BIGINT AUTO_INCREMENT PRIMARY KEY,
   username VARCHAR(50) NOT NULL UNIQUE,
   firstname VARCHAR(50) NOT NULL,
   lastname VARCHAR(50) NOT NULL,
   about TEXT,
   phone BIGINT UNIQUE,
   email VARCHAR(100) NOT NULL UNIQUE,
    profile_picture VARCHAR(208) UNIQUE ,
   gender ENUM('MALE', 'FEMALE') NOT NULL,
   birthday DATE NOT NULL,
   created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   scheduled_to_be_deleted_at DATETIME DEFAULT NULL
);
