apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      name: auth-service
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: socialmedia-auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8090

        - name: auth-db
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_PASSWORD
              value: root
            - name: MYSQL_USER
              value: mysql
            - name: MYSQL_DATABASE
              value: auth_db
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - containerPort: 3306
