services:
  auth-service:
    container_name: auth-service
    build:
      context: ${SERVICES_DIR}/auth-service
      dockerfile: ${JAVA_DOCKER_FILE}
    ports:
      - "${AUTH_SERVICE_PORT}:8080"
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 15s
      retries: 6
    depends_on:
      - auth-db
      - user-service

  auth-db:
    container_name: auth-db
    image: mysql:8.0
    volumes:
      - ${STORAGE_DIR}/auth-db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_DATABASE: auth_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "${AUTH_DB_PORT}:3306"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M